package com.epam.PlayRoom.Enum;

public enum ToyType {
  BALL_SMALL,BALL_BIG,FOOT_BALL,BASKET_BAll,VOLLEY_BALL,CAR_SMALL,CAR_BIG,CAR_MEDIUM,DOLL_MOTHER,DOLL_DAUGHTER,DOLL_FATHER,DOLL_ANIMAL,DOLL_BIG
}


